### ISSUE TITLE
about checkpoint and training details

### ISSUE THREAD

**Issue by yunzqq** [haoheliu/voicefixer_main#12]
Thank you for your awesome work

Could you provide the pre-trained check-point model?
For training, analysis and synthesis stage are trained together or separately?

**Comment by haoheliu** [comment]
Hi @yunzqq, two stages are trained separately. 
You can find the checkpoint in this repo [https://github.com/haoheliu/voicefixer](https://github.com/haoheliu/voicefixer).
Thanks for your interest.

**Comment by yunzqq** [comment]
> Hi @yunzqq, two stages are trained separately. You can find the checkpoint in this repo https://github.com/haoheliu/voicefixer. Thanks for your interest.

Thank you for your response!
For the training of vocoder, only clean speech is included or also including degraded speech?

**Comment by haoheliu** [comment]
> > Hi @yunzqq, two stages are trained separately. You can find the checkpoint in this repo https://github.com/haoheliu/voicefixer. Thanks for your interest.
> 
> Thank you for your response! For the training of vocoder, only clean speech is included or also including degraded speech?

Only clean speech is included. Thanks.

**Comment by yunzqq** [comment]
> > > Hi @yunzqq, two stages are trained separately. You can find the checkpoint in this repo https://github.com/haoheliu/voicefixer. Thanks for your interest.
> > 
> > 
> > Thank you for your response! For the training of vocoder, only clean speech is included or also including degraded speech?
> 
> Only clean speech is included. Thanks.

Thank you for your response!
