### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [haoheliu/voicefixer_main#18]
Hi,
Are you planning to eventually change this license to a more permissive license (ie ISC, MIT, etc)?
Thanks!

**Comment by fakerybakery** [comment]
Hi @haoheliu, is there any update on this? Just wondering, since the other VoiceFixer repo is licensed under MIT. Thank you

**Comment by haoheliu** [comment]
@fakerybakery I'll update it to MIT soon

**Comment by haoheliu** [comment]
Now with MIT license

**Comment by fakerybakery** [comment]
Thank you @haoheliu! Are you planning to change the AudioLDM license as well?
